apiVersion: batch/v1
kind: Job
metadata:
  name: always-fail  # This is a template
spec:
  template:
    spec:
      containers:
      - name: ml-container
        image: ubuntu:latest
        command: ["bash", "-c", "exit 1"]
        args: []  # Placeholder for arguments
        resources:
          limits:
            nvidia.com/gpu: 1
      # nodeSelector:
        # node.kubernetes.io/instance-type: n1-standard-4
        # cloud.google.com/gke-accelerator: nvidia-l4
      restartPolicy: Never
  backoffLimit: 0
