apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cpu-node-image-puller
  namespace: default
spec:
  selector:
    matchLabels:
      name: cpu-node-image-puller
  template:
    metadata:
      labels:
        name: cpu-node-image-puller
    spec:
      containers:
      - name: image-puller
        image: us-central1-docker.pkg.dev/jetrr-cloud/training-app/training-main-dev:CyberRealistic_V3
        command: ["sh", "-c", "sleep 1600"]
      nodeSelector: # Select CPU nodes by a specific label key-value that exists only on such nodes
        cloud.google.com/gke-nodepool: basic
      restartPolicy: Always # DaemonSets typically have a restart policy of Always